"""update plan and subscription tables

Revision ID: 46d551907c09
Revises: 733ac9ab35b4
Create Date: 2025-09-16 14:09:06.626390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d551907c09'
down_revision: Union[str, Sequence[str], None] = '733ac9ab35b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('wave_payment_link_monthly', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('wave_payment_link_yearly', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('wave_transaction_id', sa.String(), nullable=True))
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'wave_transaction_id')
    op.drop_column('plans', 'wave_payment_link_yearly')
    op.drop_column('plans', 'wave_payment_link_monthly')
    # ### end Alembic commands ###
